name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dwarburton/awscli
        username: dwarburton
        password: ${{ secrets.DOCKER_PASSWORD }}
